name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    name: Install, Lint, Test, Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Install dependencies
        working-directory: app
        run: |
          npm ci || npm install

      - name: Lint
        working-directory: app
        run: npm run lint --if-present

      - name: Run tests
        working-directory: app
        env:
          CI: true
        run: npm test -- --reporter=default

      - name: Build
        working-directory: app
        run: npm run build

      - name: Artifact dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
            name: skolapp-dist-${{ matrix.node-version }}
            path: app/dist
            if-no-files-found: error

  smoke-preview:
    name: Smoke Preview Build (single Node)
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install & Build
        working-directory: app
        run: |
          npm ci || npm install
          npm run build
      - name: List dist files
        run: ls -R app/dist | head -n 100
